export enum MessageTypeEnum {
  TEXT = 'TEXT',
  AUDIO = 'AUDIO',
  IMAGE = 'IMAGE',
  FILE = 'FILE',
  BID = 'BID',
  SYSTEM = 'SYSTEM',
}

export enum OrderStatusEnum {
  DRAFT = 'DRAFT',
  INVITATION_SENT = 'INVITATION_SENT',
  INVITATION_ACCEPTED = 'INVITATION_ACCEPTED',
  PENDING_CONFIRMATION = 'PENDING_CONFIRMATION',
  CLIENT_APPROVED = 'CLIENT_APPROVED',
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  DISPUTED = 'DISPUTED',
}

export enum OrderItemStatusEnum {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum OrderItemImportanceLevelEnum {
  ADDON = 'ADDON',
  NECESSITY = 'NECESSITY',
  ABSOLUTE_NECESSITY = 'ABSOLUTE_NECESSITY',
}

export enum InvitationStatusEnum {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  DECLINED = 'DECLINED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
}

export enum InvoiceStatusEnum {
  PENDING = 'PENDING',
  PAID = 'PAID',
  OVERDUE = 'OVERDUE',
}

export enum OrderInviteMediumEnum {
  EMAIL = 'EMAIL',
  PHONE = 'PHONE',
}

export const ORDER_JOB_NAMES = {
  ORDER_INVITATIONS_EXPIRATION_HANDLER: 'ORDER_INVITATIONS_EXPIRATION_HANDLER',
  PROCESS_ORDER_STATUS_CHANGE: 'PROCESS_ORDER_STATUS_CHANGE',
};

export class BidDetails {
  amount: number;
  currency: string;
}
